workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Reset iOS Pods
        script: |
          cd ios
          # Eski lock fayllarni va keshni butunlay o'chirib tashlaymiz
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/.cocoapods
          
          # Yangidan repo-larni yuklab olamiz
          pod repo update
          pod install --repo-update
          cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --no-codesign
    publishing:
      email:
        recipients:
          - karshievdev@gmail.com
