workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest # Xcode versiyasini belgilaydi
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build ipa
        script: |
          # --no-codesign qismi hozircha sertifikatingiz bo'lmasa xatolik bermasligi uchun
          flutter build ipa --release --no-codesign
    publishing:
      email:
        recipients:
          - karshievdev@gmail.com # O'z emailingizni yozing