workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and Get Flutter packages
        script: |
          # Kernel snapshot xatosini oldini olish uchun hamma narsani tozalaymiz
          flutter clean
          flutter pub get
          # Realm binar fayllarini iOS uchun majburiy yuklash
          dart run realm install --target-os-type ios
      - name: Reset iOS Pods
        script: |
          cd ios
          # Eski bog'liqliklarni va keshni butunlay o'chirib tashlaymiz
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          
          # CocoaPods repolarini yangilash va toza o'rnatish
          pod repo update
          pod install --repo-update
          cd ..
      - name: Flutter build ipa
        script: |
          # Build jarayoni - toza kesh bilan boshlanadi
          flutter build ipa --release --no-codesign
    publishing:
      email:
        recipients:
          - karshievdev@gmail.com
