name: strawberryhrm
description: A new Flutter project.
publish_to: 'none'

version: 2.1.2+26

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  cached_network_image: ^3.4.1
  formz: ^0.8.0
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  country_picker: ^2.0.27
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_datepicker: ^32.2.9
  syncfusion_flutter_signaturepad: ^32.2.9
  meta_club_api:
    path: packages/data/meta_club_api
  user_repository:
    path: packages/data/user_repository
  location_track:
    path: packages/feature/location_track
  qr_attendance:
    path: packages/feature/qr_attendance
  selfie_attendance:
    path: packages/feature/selfie_attendance
  chat:
    path: packages/feature/chat
  lottie: ^2.4.0
  core:
    path: packages/core
  presentation:
    path: packages/presentation
  hrm_framework:
    path: packages/hrm_framework
  domain:
    path: packages/domain
  authentication_repository:
    path: packages/data/authentication_repository
  offline_attendance:
    path: packages/feature/offline_attendance
  offline_location:
    path: packages/feature/offline_location
  notification:
    path: packages/feature/notification
  dio_service:
    path: packages/data/dio_service
  voice_io:
    path: packages/feature/voice_io
  flutter_tts: ^3.8.0
  speech_to_text: ^7.0.0
  flutter_lints: ^6.0.0
  photo_view: ^0.14.0
  fluttertoast: ^8.0.9
  image_picker: ^1.0.4
  flutter_svg: ^2.1.0
  upgrader: ^12.5.0
  page_transition: ^2.0.4
  google_fonts: ^8.0.2
  font_awesome_flutter: ^11.0.0
  toggle_switch: ^2.0.1
  easy_localization: ^3.0.2
  shimmer: ^3.0.0
  custom_timer: ^0.2.3
  google_maps_flutter: ^2.5.0
  firebase_performance: ^0.10.0+8
  firebase_core: ^3.5.0
  firebase_analytics_platform_interface: ^4.2.5
  firebase_core_platform_interface: ^6.0.2
  firebase_analytics: ^11.3.3
  pull_to_refresh: ^2.0.0
  dotted_border: ^3.1.0
  month_year_picker: ^0.5.0+1
  flutter_html: any
  connectivity_plus: ^6.1.0
  flutter_screenutil: ^5.8.4
  syncfusion_flutter_gauges: ^32.2.9
  flutter_local_notifications: ^19.1.0
